---
name: Update plugins

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - run: echo "::set-output name=stdout::$(./bin/update-plugins.sh)\n"
        id: update-plugins
        name: Update plugins

      - uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f
        id: generate-token
        with:
          app_id: ${{ secrets.JENKINS_ADMIN_APP_ID }}
          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 #v5
        with:
          commit-message: 'chore(deps): update plugins'
          signoff: false
          title: 'chore(deps): update plugins'
          author: jenkins-infra-updatecli[bot] <178728+jenkins-infra-updatecli[bot]@users.noreply.github.com>
          committer: jenkins-infra-updatecli[bot] <178728+jenkins-infra-updatecli[bot]@users.noreply.github.com>
          branch: update-plugins
          token: ${{ steps.generate-token.outputs.token }}
          labels: dependencies,plugins
          body: |
            Changes:
            ```diff
            ${{ steps.update-plugins.outputs.stdout }}
            ```
